### ISSUE TITLE
Please delete the reference to this repo in arXiv:2310.16898

### ISSUE THREAD

**Issue by jingtaow** [liangyn22/MCUFormer#1]
Could you please delete the reference to this repo in [arXiv:2310.16898](https://arxiv.org/abs/2310.16898)? It is misleading to refer to a github repo when there is only a README file in the repo. You may always update the arxiv paper after the project is truly open sourced Thanks.

**Comment by liangyn22** [comment]
I'm so sorry that I do not release the code immediately. I will also release the code of engine in few days.
